[compiler.solc]
include_paths = [
    "source-v2/node_modules",
]
remappings = [
    "contracts/=source-v2/contracts/",
]
exclude_paths = [
    "source-v2/node_modules"
]

[compiler.solc.optimizer]
enabled = true
